name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7', '3.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with: { ruby-version: '${{ matrix.ruby }}' }

      - name: Setup project
        run: bin/setup

      - name: Run tests
        run: bin/rake ci
        env:
          SIMPLECOV: '1'

      - name: Report to CodeClimate
        if: matrix.ruby == 2.7
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: '${{ secrets.CC_TEST_REPORTER_ID }}'
